# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/g2f_comp_2023',
                'doc_host': 'https://danielkick.github.io',
                'git_url': 'https://github.com/danielkick/g2f_comp_2023',
                'lib_path': 'g2f_comp_2023'},
  'syms': {'g2f_comp_2023.core': {'g2f_comp_2023.core.foo': ('core.html#foo', 'g2f_comp_2023/core.py')}}}
